service: aws-lambda-probe

plugins:
  - serverless-scriptable-plugin

provider:
  name: aws
  runtime: nodejs20.x

  region: ap-northeast-1
  stage: dev

  memorySize: 256
  architecture: arm64

  logRetentionInDays: 1
  versionFunctions: false
  timeout: 5

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"

    STAGE: ${self:provider.stage}
    NODE_ENV: production

package:
  individually: true
  patterns:
    - "!**"
    - "!node_modules/**"

functions:
  http:
    handler: artifact/handlers.http
    url: true
    package:
      patterns:
        - artifact/handlers.mjs*
    events:
      - httpApi:
          method: ANY
          path: /
      - httpApi:
          method: ANY
          path: /{pathname+}

custom:
  scriptHooks:
    before:package:createDeploymentArtifacts: pnpm artifact
